runner:
  phpcs:
    cmd: |
      ./vendor/bin/phpcs --error-severity=0 --standard=./phpcs.xml --report=emacs
    errorformat:
      - "%f:%l:%c: %m"

  phpstan:
    cmd: |
      ./vendor/bin/phpstan analyse -n --no-progress --error-format=raw
