version: 2.1

executors:
  default:
    docker:
      - image: circleci/php:7.1-browsers
        environment:
          REVIEWDOG_VERSION: "0.9.11"

    working_directory: ~/repo

commands:
  restore_composer:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

  install_reviewdog:
    steps:
      - run: curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./reviewdog

jobs:
  build:
    executor:
      name: default

    steps:
      - checkout
      - restore_composer

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

  phpcs:
    executor:
      name: default

    steps:
      - checkout
      - restore_composer

      - run: ./vendor/bin/phpcs --warning-severity=0 --standard=./phpcs.xml --report=code --report-width=120

  phpstan:
    executor:
      name: default

    steps:
      - checkout
      - restore_composer

      - run: ./vendor/bin/phpstan analyse -n --no-progress

  phpmd:
    executor:
      name: default

    steps:
      - checkout
      - restore_composer

      - run: ./vendor/bin/phpmd ./src text ./phpmd.xml

  reviewdog:
    executor:
      name: default

    steps:
      - checkout
      - restore_composer
      - install_reviewdog

      - run: ./reviewdog -conf=./.reviewdog.yml -reporter=github-pr-review

workflows:
  build-and-test:
    jobs:
      - build

      #      - phpcs:
      #          requires:
      #            - build
      #
      #      - phpstan:
      #          requires:
      #            - build

      - phpmd:
          requires:
            - build

      - reviewdog:
          requires:
            - build
#            - phpcs
#            - phpstan
